package.json
In order to maintain compatibility with projects using react v0.14.0, we want to use the react version installed on the owner's project. This also prevents a separate version of react being packaged with react-markdown.
=> Move react dependency to peerDependencies

README.md, src/react-markdown.js, test/react-markdown.test.js
I ran into issues when making a `label` element that was rendered using `ReactMarkdown`, not being able to add, eg., the `htmlFor` prop.
This pull request enables a `props` prop object on the `ReactMarkdown` component.
```
<ReactMarkdown containerTagName="label" props={{htmlFor: "myElementID"}} source="This is my **label**" />
```
=> Add `props` object to allow props on container element such as `id` and `htmlFor`

README.md, src/react-markdown.js, test/react-markdown.test.js
In some cases, I'd find it useful to render children *before* and/or *after* the rendered markdown, yet *within the same container element*.
**Simple pseudo example:**
```
var childBefore = (<img src="avatar.png" alt="User avatar" />);
<ReactMarkdown source="**Hello**" containerTagName="div" childBefore={childBefore} />
```
```
<div>
<strong>Hello</strong>
</div>
```
=> Add `childBefore` and `childAfter` props

src/react-markdown.js
This comes in handy when you need to do destructive updates for the AST and have to call `walker.resumeAt` afterwards.
=> Pass the walker to the walker callback function

react-markdown.d.ts, test/react-markdown-test.tsx
`react-markdown` do not work with TypeScript using default configuration.
I fix it. Please check and merge this.
=> BugFix: Type interpretation has broken

src/react-markdown.js, test/react-markdown.test.js
This allows the component to send parser options to the Commonmark parser (in particular I'm interested in getting the smart-quotes parser, but there are other options that may be useful for others).
=> Added ability to pass options to the parser.

src/react-markdown.js
Hi! :wave: Thanks for creating this component!
The `React.createClass` method is going to be deprecated soon and will
be removed in React v16.
https://github.com/facebook/react/pull/9232
This patch changes the component to a class extended from
`React.Component`. It does it manually by assigning to the prototype,
to avoid introducing a compile step.
e; Oops, goofed up the title there with `hub pull-request` :sweat_smile:
=> Remove `React.createClass`

react-markdown.d.ts, src/ast-to-react.js
Currently `transformLinkUri` can be provided for custom URL transformations, but not all available arguments are passed.
This makes it impossible to provide custom URL transformation logic, based on the URL title and content.
With this change both children and title are provided to the `transformLinkUri` (without changing the default `uriTransformer` implementation
=> transformLinkUri - provide all available arguments

src/ast-to-react.js
currently, the transform function is not yet applied for referenced images
=> enable transformImageUri also for image references, not only direct images

README.md, src/ast-to-react.js, test/react-markdown.test.js
If you override the text renderer with a function that returns a React Element, you'll get a "unique key error" warning if you don't pass in a key.
This commit passes the key that `astToReact` gives to every other node to the text renderer function. If you are simply returning a string from your renderer function, you can just ignore the extra parameter.
Note: another way to fix this would be to have the text renderer accept a React Component like the rest of the renderers. That would be a breaking change at this point though.
The current README docs are slightly wrong.
When you override the `text` renderer it expects a function, but the docs imply that it always takes a React Component. If you pass it a React Component you will get an error.
This PR lets users know that they should pass …
=> Pass the React Key into an overridden text renderer and update the README

src/ast-to-react.js, test/__snapshots__/react-markdown.test.js.snap, test/react-markdown.test.js
This PR updatest `astToReact` so that it supports passing `React.Fragment` as a renderer without wrapping it in a function.
=> Add support for fragment renderers

index.d.ts, src/ast-to-react.js, src/react-markdown.js
1. Match the unified API use `unified().use(params1).use(params2)...` with `plugins: [ [ params1 ], [ params2 ], ... ]`
2. Support for `remark-iframes` options. Example usage: `plugins: [ remarkIframes, { 'www.youtube.com': {...} } ]`
3. Update TypeScript definition.
=> Update TypeScript definition and prop types

README.md
Had to dig into the source code to find whether I could pass `children` as the Markdown source, and thought it'd be nice to state that you can in the docs.
=> Clarifies in the README that a children prop is accepted as an option to source

src/plugins/disallow-node.js
This fixes a scenario when a disallowed node does not have children. Current code will evaluate `node.children` and add undefined to  `parent.children`'s array. This should not happen because the consumer code relies on a child not being `undefined`.
This problem manifests only when mode is `unwrap`.
An example of child with this problem is `thematicBreak` (`source: "***"`)
=> Fix bug with some disallowed nodes

src/ast-to-react.js, test/__snapshots__/react-markdown.test.js.snap, test/react-markdown.test.js
Fix bug when in markdown template presents empty link reference `[][]`
For such values at time of mapping syntax tree to react components in this line
https://github.com/rexxars/react-markdown/blob/master/src/ast-to-react.js#L57
`node. identifier` is empty string and as result `ref` will be `null`.  As result later in line 
https://github.com/rexxars/react-markdown/blob/master/src/ast-to-react.js#L105
at time of getting `ref.href` application will throw exception.
Fixed it. Test case added.
=> FIX: parsing empty link references

src/ast-to-react.js
Thank you for this library! I have tried to use other React libraries for rendering markdown in React *Native*, but many fell short. Thanks to *remark*, I have now found a robust way of manipulating Markdown before rendering.
This library apparently is meant only for React DOM, but I have found a way of supporting RN. Basically the biggest challenge lies with avoiding `<View>` inside `<Text>`, which is not allowed on RN for Android. On the web it's not a big deal to have, e.g., `<div>` inside `<span>`, so that's why this library works fine for the web. In particular, one of the tricky things to render are nested lists, e.g.:
```
- First
- Second
- 2a
- 2b
- Third
```
I made https://gitlab.com/staltz/mdast-normalize-react-native which transforms the AST so that it avoids complicated AST …
=> Add more metadata props to list and listItem

README.md, src/ast-to-react.js, src/react-markdown.js, test/__snapshots__/react-markdown.test.js.snap, test/react-markdown.test.js
Addresses issue #146 by adding a `linkTarget` attribute to default the target attribute for all links.
This can also be set to a function to support the case where links to specific domains should open in new tabs but not other links.
I considered the url parsing strategy suggested in #146 but did not implement it as it's non-standard markdown. I believe a better approach would be to use a mdast plugin.
=> Add target attribute to links [#146]

README.md, src/ast-to-react.js, test/__snapshots__/react-markdown.test.js.snap, test/react-markdown.test.js
When `indexUnderParent` prop is `true`, pass `indexUnderParent` and `parentChildCount` props to non-tag renderers.
Resolves #213
=> Add support for passing index info to renderers

index.d.ts
Since [renderers for arbitrary node types are allowed](https://github.com/rexxars/react-markdown/issues/162), the typings should reflect this.
=> Allow arbitrary renderer types

README.md
I tried using a plugin with react-markdown, and only after finding https://github.com/rexxars/react-markdown/issues/188#issuecomment-404710893 did I learn that it was not going to work as the plugin I was hoping to use was using `transform`. Thus, it might be a good idea to be more upfront about it, to prevent unnecessary work.
(Of course this note can be removed again if someone does find a solution to support non-parsing plugins.)
=> Add note about only parsing plugins working

package-lock.json, package.json, src/ast-to-react.js, test/react-markdown.test.js
Fix for the following from https://github.com/rexxars/react-markdown/issues/270:
```
Invariant Violation: img is a void element tag and must neither have children nor use dangerouslySetInnerHTML.
```
The trick is to avoid passing a `children` argument _at all_ to React's `createElement`/`cloneElement` when there are none (`[]` and `undefined` are treated as children by React)
=> Fix void element children invariant violation

src/plugins/html-parser.js, test/__snapshots__/react-markdown.test.js.snap, test/react-markdown.test.js
From https://github.com/rexxars/react-markdown/issues/270 this fixes
```
TypeError: undefined is not an object (evaluating fromNode.node.position.start)
```
=> Fix HTML parsing of multiple void elements

src/plugins/html-parser.js, test/__snapshots__/react-markdown.test.js.snap, test/react-markdown.test.js
In `parseNode()` from `html-parser.js` we first match against `closingTagRe` to push onto `open` to indicate we're in a non-void element.
However, if on the matching opening tag you return an element — from `parser.parseWithInstructions()` — with a different tag as what was matched by `closingTagRe`, or a custom React component (where `type` is no longer a string), you can't close off the matched non-void element.
=> Fix matching of replaced non-void elements in HTML parser plugin

src/ast-to-react.js, test/__snapshots__/react-markdown.test.js.snap, test/react-markdown.test.js
With a single child `el.props.children` isn't an array so `.concat()` fails
=> Fix HTML parsing of elements with a single child vs. multiple children

index.d.ts
This PR was created because typescript is throwing erros when assigning null to transformLinkUri or transformImageUri. This should be possible though as stated in the documentation.
=> Update Typings: Make transformLinkUri & transformImageUri actually nullable

index.d.ts
WIth https://github.com/rexxars/react-markdown/commit/fe0b57a8e8e7256446419e2d49064a78c6d19479 commit, there was introduced `parserOptions` property with `RemarkParserOptions` type.
There is typo in the interface name - should be: `RemarkParseOptions`
=> Fix for remark-parse/types has no exported member RemarkParserOptions

readme.md
Remove the phrase "which adds support for" in the readme which was repeated twice
=> Remove redundant phrase in readme

src/ast-to-react.js, test/react-markdown.test.js
I have noticed that if your html is incorrect - starts with close tag, the solution crushes,
I thought it might be better to just skip the problematic tag with empty div or fragment
=> Fix exception on missing element from `html-to-react`

package.json, test/__snapshots__/react-markdown.test.js.snap, test/react-markdown.test.js
it was only used for one test, and does not appear to be needed.
This unblocks https://github.com/remarkjs/react-markdown/pull/498#issuecomment-716186190
=> test: drop enzyme as dependency

src/index.js
including an example of GitHub flavored markdown in the CommonMark demo leads to confusion (see https://github.com/remarkjs/react-markdown/issues/529, https://github.com/remarkjs/react-markdown/issues/524, https://github.com/remarkjs/react-markdown/issues/525, https://github.com/remarkjs/react-markdown/issues/526).
This removes GFM from the commonmark demo to reduce confusion.
An alternative could be to add a toggle to enable/disable `remark-gfm` on the demo site.
=> docs: remove github flavored table from example/demo of commonmark

readme.md
close #542 
Fix `uri-transformer.js` link on README.
=> Fix `uri-transformer.js` link on README

package.json, src/ast-to-react.js, src/plugins/html-parser.js, src/react-markdown.js, src/renderers.js, src/with-html.js
* Add restriction to ES 2015
* Use `Object.assign` instead of `xtend`
* Require `React.Fragment`
* Remove hacks needed for React 15
=> Remove old polyfills

.eslintignore, .gitignore, .prettierignore, package.json
I don’t think we need a prebuilt `lib/`; the source code is usable as-is
=> Remove compiled library

src/ast-to-react.js, test/__snapshots__/react-markdown.test.js.snap, test/react-markdown.test.js
React Markdown 6.0.0 with Remark Parse 9.0.0, Remark Rehype 8.1.0, Remark
GFM 1.0.0 and React 17.0.2 would cause warnings in the developer console:
> Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a
> child of `<table>`. Make sure you don't have any extra whitespace between
> tags on each line of your source code.
In fact `<table>`, `<tbody>`, `<thead>`, `<tr>` all do not permit any text
elements to appear directly inside them.  See e.g.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table
Hence we strip any text element from the children of these elements
unconditionally.
Closes: https://github.com/remarkjs/react-markdown/issues/576
=> Fix whitespace in table elements

src/ast-to-react.js
Hello.
Thank you for the very nice package.
Thanks to react-markdown, my development is going very smoothly.
I added the `className` to the `CodeComponent` type because it is not defined in the script, while it is in `README.md`.
I have confirmed that it works on my environment, so I would be happy if you could adopt it.
Thank you for your consideration.
=> Add string type for `className`s

readme.md
Fixed SyntaxHighlighter example in readme.md not rendering inline code, see See remarkjs#587
=> Fix syntax highlighting example in readme.md

src/ast-to-react.js, test/react-markdown.test.js
follow up to https://github.com/remarkjs/react-markdown/pull/623#pullrequestreview-717272026
=> Fix type to include each element w/ its properties

lib/ast-to-react.js, lib/complex-types.ts, test/test.jsx
Follow up to https://github.com/remarkjs/react-markdown/issues/666#issuecomment-1001578251 removing `ref` from element props.
Leverages `ComponentPropsWithoutRef` which is a wrapper around `IntrinsicElements` which picks component properties from it.
=> Fix `ref` in types

lib/react-markdown.js, package.json, readme.md, test/test.jsx
This PR updates `remark-rehype` to v10, and adds options passthrough to `remark-rehype`.
This is to enable new options such as `clobberPrefix`, which is needed when rendering more than one Markdown document on a page (e.g. comments).
Attempted to follow the guidelines and current code structure as much as I could.
=> Add support for passing options to `remark-rehype`

lib/react-markdown.js
Follow-up to https://github.com/remarkjs/react-markdown/pull/675. Adds `| undefined` as suggested in https://github.com/microsoft/TypeScript/issues/48242#issuecomment-1067348119.
Fixes this build error:
```
ERROR in ../../.yarn/__virtual__/react-markdown-virtual-1089d10e66/0/cache/react-markdown-npm-8.0.0-3d725f3756-61412ecd18.zip/node_modules/react-markdown/lib/react-markdown.d.ts 47:32-56
TS2307: Cannot find module 'mdast-util-to-hast/lib' or its corresponding type declarations.
45 |   remarkPlugins?: import('unified').PluggableList | …
```
=> Fix TypeScript bug by adding workaround

lib/react-markdown.js, test/test.jsx
This PR extends the prop-types of rehypePlugins and remarkPlugins to support strings and arrays of strings. See https://github.com/remarkjs/remark/discussions/945
=> Fix prop types of plugins

readme.md
Included `alt` as one of the attributes expected in the `img` component as this component outputs both `alt` AND `title`. Not having both can be misleading specially since `alt` is what's most often/easily used when creating an image in markdown `[!alt](src "title")`. The use of alt over title comes not only from practicality but also due to accessibility. Additionally, removed parenthesis as it read better now that there wasn't just one item.
=> Add clarification of `alt` on `img` in docs

lib/ast-to-react.js
Addresses #713 . Specify "th" and "td" props based off html elements. `ast-to-react.d.ts` will look like:
```
export type TableDataCellProps = ComponentPropsWithoutRef<'td'> &
ReactMarkdownProps & {
style?: Record<string, unknown>
isHeader: false
}
export type TableHeaderCellProps = ComponentPropsWithoutRef<'th'> &
ReactMarkdownProps & {
style?: Record<string, unknown>
isHeader: true
}
(...)
export type TableDataCellComponent = ComponentType<TableDataCellProps>
export type TableHeaderCellComponent = ComponentType<TableHeaderCellProps> …
```
=> fix "th" and "td" type definitions based off native elements

lib/react-markdown.js
Signed-off-by: Marc Espín <mespinsanz@gmail.com>
Change the `to` of the plugins deprecation message. It should be `remarkPlugins` instead of `plugins`. It doesn't make sense to migrate from `plugins` to `plugins`.
This is the message that I got:
=> Fix typo in `plugins` -> `remarkPlugins` deprecation message

lib/ast-to-react.js, test/test.jsx, tsconfig.json
Updates TypeScript configuration to use node16 resolution for ESM.
=> Update to use `node16` module resolution in `tsconfig.json`

readme.md
Improves README syntax highlighting example. The current example produces a TypeScript error by default. See here: https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/479#issuecomment-1267772279
=> Improve README syntax highlight example

lib/ast-to-react.js
See in particular the [first](https://github.com/remarkjs/react-markdown/issues/703#issue-1337513642) and [currently last](https://github.com/remarkjs/react-markdown/issues/703#issuecomment-1503218171) post in the related issue.
Closes GH-703.
=> Fix performance for keys

lib/ast-to-react.js, lib/react-markdown.js, readme.md, test/test.jsx
Following the discussion in https://github.com/remarkjs/react-markdown/pull/761, I removed the redundant `linkTarget` prop.
This functionality can still be applied using plugins, or the `components` prop.
=> Removing `linkTarget` option

lib/index.js, test.jsx
This replaces `@typedef` tags with `@import` where applicable. `@import` tags were introduced in TypeScript 5.5.
=> Refactor to use `@import` to import types

lib/index.js, test.jsx
This makes the `react-markdown` types compatible with React 19. Dependencies still rely on the `JSX` namespace, but let’s trackle one thing at a time.
The better return type would be `ReactNode`, not `ReactElement`. But that breaks compatibility with TypeScript < 5.1. Let’s do that in a semver major.
=> Replace `JSX` global with explicit `ReactElement`

package.json
- added remark-gfm as dev dependency
added `remark-gfm` as dev dependency to fix the unit tests.
=> Add missing dev-dependency

lib/index.js
This change separates all typedefs into their own JSDoc blocks. Having them in the same block, can be problematic sometimes. For example when they contain `@template` tags.
=> Separate all typedefs into their own JSDoc blocks

index.js, lib/index.js
This adds support for React 19 types, by removing the dependency on the types provided by hast-util-to-jsx-runtime, thus removing the dependency on the JSX global namespace.
Unfortunately the current setup doesn’t really allow testing the types against multiple React versions. #838 would enable that.
Closes #877
=> Add support for React 19

lib/index.js
The way we used `ElementType` caused a significant increase of resource usage for TypeScript.
I can’t really explain it, but this fixes it. I’m personally inclined to say people should avoid using the `JSX` namespace, but I see no other way around it.
Without this change, autocompletion in my editor takes a noticable time to load. Now it’s instant.
On my machine this halves the time of running `tsc -b` from ~15s to ~7s.
Closes #883
=> Optimize the Components type

lib/index.js, test.jsx
Running asynchronous code inside a `useEffect` causes race conditions. This is now handled correctly.
=> Handle race conditions in MarkdownHooks

index.js, lib/index.js, test.jsx
The `<MarkdownHooks/>` component now supports a new prop named `fallback`. This fallback is displayed while the initial content hasn’t loaded yet. The name `fallback` was chosen to match the same prop from `<Suspense/>`.
=> Add MarkdownHooks fallback prop

lib/index.js
Some plugins may perform heavy work in preparation to make the transformer light-weight. A good example of this is `rehype-starry-night`.
Without this change, an interactive markdown editor which includes `rehype-starry-night` is very sluggish. With this change, performance is as good as if `rehype-starry-night` isn’t even used.
Fix https://github.com/orgs/rehypejs/discussions/194
=> Memoize the processor in MarkdownHooks
