package.json
react-markdown.d.ts
test/react-markdown-test.tsx

Hi, this is definitions for TypeScript.

Add TypeScript definitions.

---

react-markdown.d.ts

fix: Too strict TS type

---

src/ast-to-react.js
test/__snapshots__/react-markdown.test.js.snap
test/react-markdown.test.js

Tight lists with sublist

---

src/wrap-table-rows.js
test/__snapshots__/react-markdown.test.js.snap
test/react-markdown.test.js

https://github.com/rexxars/react-markdown/issues/126

Fixed partial table exception

---

src/ast-to-react.js
src/renderers.js
test/__snapshots__/react-markdown.test.js.snap
test/react-markdown.test.js

Having a text renderer can help to add more functionnalities (issue #61)

Allow text renderer

---

index.d.ts

Matching with NodeTypes in readme https://github.com/rexxars/react-markdown#node-types

Add 'text' to index.d.ts NodeType

---

index.d.ts

Testing this now, please hold of merging for a minute ☺️

Fix TypeScript index signature for renderers

---

src/ast-to-react.js
test/__snapshots__/react-markdown.test.js.snap

Fixes https://github.com/rexxars/react-markdown/issues/158

Output paragraph element for last item in loose list.

---

README.md

Fix npm link in README

---

index.d.ts

Add parserOptions to types file

---

index.d.ts

Add typescript definition for html-parser

---

index.d.ts
with-html.d.ts

As @petersowa pointed out in https://github.com/rexxars/react-markdown/pull/352#pullrequestreview-337828385 , I made a mistake in #352 . This should fix the bug.
Fixes #377

Fix typescript declaration

---

README.md

Updated remark-parse github link

---

index.d.ts
package.json
react-markdown-types-test.tsx
tsconfig.json
tslint.json
with-html.d.ts

test(types): add dtslint tests to verify typescript typings

---

index.d.ts
react-markdown-types-test.tsx

Move disallowedTypes into base props in typings

---

rollup.config.js

Fix umd browser build

---

changelog.md
package.json
src/react-markdown.js
test/react-markdown.test.js

[Show rendered changelog](https://github.com/remarkjs/react-markdown/blob/changelog/changelog.md)

Update changelog for v6

---

readme.md

Document flow of data through react-markdown, the goal being to clarify how remark, remark-rehype, and components fit together.

Add architecture section to readme

---

src/ast-to-react.js

flagged by CI at https://github.com/remarkjs/react-markdown/runs/2821479099#step:5:16

Fix type failure introduced by TS in patch

---

lib/react-markdown.js
package.json
readme.md

[View rendered](https://github.com/remarkjs/react-markdown/blob/docs/readme.md)
Related-to: unifiedjs/unified#168.
/cc @nemo-omen @remcohaszing @ChristianMurphy @Murderlon @with-heart @joostdecock @mgan59

Add improved docs

---

lib/ast-to-react.js
package.json

Fixes a type error that is new in TypeScript 5.0:
```
ERROR in node_modules/react-markdown/lib/ast-to-react.d.ts:17:44
TS2344: Type 'T' does not satisfy the constraint 'ElementType<any>'.
Type 'T' is not assignable to type 'FunctionComponent<any>'.
15 |  */
16 | export type ComponentPropsWithoutRef<T> =
> 17 |   import('react').ComponentPropsWithoutRef<T>
|                                            ^
18 | export type ReactNode = import('react').ReactNode
19 | export type Position = import('unist').Position
20 | export type Element = …
```

Update to TS 5

---

.github/workflows/main.yml
package.json

Update build tools, lint tools, and CI/CD tools.
In the process this should resolve https://github.com/orgs/remarkjs/discussions/1286#discussioncomment-8375860

Update website dependencies

---

changelog.md

I really enjoyed using this project, nice work! Caught a couple of typos in the changelog.md though 😛

Update changelog.md, fix typo(s)
